
#ifndef MCAL_EXT_INT_EXT_INT_PRIVATE_H_
#define MCAL_EXT_INT_EXT_INT_PRIVATE_H_

#define FALLING_EDGE	 1
#define RISING_EDGE		 2
#define LOW_LEVEL        3
#define LOGICAL_CHANGE   4

#endif /* MCAL_EXT_INT_EXT_INT_PRIVATE_H_ */
