
#ifndef MCAL_EXT_INT_EXT_INT_CONFIG_H_
#define MCAL_EXT_INT_EXT_INT_CONFIG_H_

#include "Ext_Int_Private.h"

/* Select External interrupts sense control: FALLING_EDGE, RISING_EDGE, LOW_LEVEL, LOGICAL_CHANGE */
#define EXT_INT0_SENSE_CONTROL RISING_EDGE
#define EXT_INT1_SENSE_CONTROL RISING_EDGE
#define EXT_INT2_SENSE_CONTROL RISING_EDGE

#endif /* MCAL_EXT_INT_EXT_INT_CONFIG_H_ */
